#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>

#include <libspotify/api.h>
#include <event2/event.h>

#include "spotify.h"

#define USER_AGENT "Futify"
#define VERSION "0.1"

struct spotify_s {
	struct event_base *event_base;

	struct event *stop_event;
	struct event *process_event;

	sp_session *session;
};

#include "spotify_api_callbacks.c"
#include "spotify_event_callbacks.c"

spotify_t *
spotify_init(int *error)
{
	spotify_t *spotify;
	sp_session_config config;
	sp_error sp_error;

	memset(&config, 0, sizeof(sp_session_config));
	memset(&sp_error, 0, sizeof(sp_error));

	if (error) *error = 0;
	spotify = calloc(1, sizeof(spotify_t));
	if (!spotify) {
		if (error) *error = 1;
		return NULL;
	}

	spotify->event_base = event_base_new();
	if (!spotify->event_base) {
		if (error) *error = 2;
		return NULL;
	}
	register_event_callbacks(spotify);

	/// The application key is specific to each project, and allows Spotify
	/// to produce statistics on how our service is used.
	extern const char g_appkey[];
	/// The size of the application key.
	extern const size_t g_appkey_size;

	// Always do this. It allows libspotify to check for
	// header/library inconsistencies.
	config.api_version = SPOTIFY_API_VERSION;

	// The path of the directory to store the cache. This must be specified.
	// Please read the documentation on preferred values.
	config.cache_location = "tmp";

	// The path of the directory to store the settings. 
	// This must be specified.
	// Please read the documentation on preferred values.
	config.settings_location = "tmp";

	// The key of the application. They are generated by Spotify,
	// and are specific to each application using libspotify.
	config.application_key = g_appkey;
	config.application_key_size = g_appkey_size;

	// This identifies the application using some
	// free-text string [1, 255] characters.
	config.user_agent = USER_AGENT" "VERSION;

	// Register the callbacks.
	config.callbacks = &callbacks;

	// Set the userdata to our spotify handle
	config.userdata = spotify;

	sp_error = sp_session_create(&config, &spotify->session);
	if (sp_error != SP_ERROR_OK) {
		fprintf(stderr, "failed to create session: %s\n",
		                sp_error_message(sp_error));

		if (error) *error = 0x20;
		free(spotify);
		return NULL;
	}
	return spotify;
}

void
spotify_login(spotify_t *spotify, const char *username, const char *password)
{
	sp_error error;

	if (!spotify) {
		return;
	}
	error = sp_session_login(spotify->session, username, password, 0, NULL);
	if (error != SP_ERROR_OK) {
		fprintf(stderr, "failed to login: %s\n",
		                sp_error_message(error));
	}
}

void
spotify_logout(spotify_t *spotify)
{
	sp_error error;

	if (!spotify) {
		return;
	}
	error = sp_session_logout(spotify->session);
	if (error != SP_ERROR_OK) {
		fprintf(stderr, "failed to logout: %s\n",
		                sp_error_message(error));
	}
}

void
spotify_destroy(spotify_t *spotify)
{
	if (spotify) {
		sp_session_release(spotify->session);
		event_base_free(spotify->event_base);
	}
	free(spotify);
}

int
spotify_run(spotify_t *spotify)
{
	if (!spotify) {
		return -1;
	}
	return event_base_dispatch(spotify->event_base);
}

void
spotify_stop(spotify_t *spotify)
{
	if (spotify) {
		event_active(spotify->stop_event, 0, 0);
	}
}

